### ISSUE TITLE
current_through_path in DynamicsData

### ISSUE THREAD

**Issue by omedeiro** [loganbvh/py-tdgl#23]
Can the current_through_path be calculated while solving and plotted similarly to DynamicsData.plot()?

**Comment by loganbvh** [comment]
`DynamicsData` stores the voltage, phase difference, and time step for *every* solve step, whereas the full dataset is saved only every `options.save_every` time steps. I think calculating the current through a path at every time step would slow the solver down significantly.

The easiest thing to do would be to add a standalone function (or static method on `tdgl.Solution`) with signature like 
```python
get_current_through_paths(
    solution_group_or_path: Union[h5py.File, os.PathLike],
    paths: Union[np.ndarray, list[np.ndarray]],
) -> Union[float, list[float]]
```
that calculates the total current through one or more paths for each saved time step in a solution. This would be called after a full simulation has been performed and saved.

Would that work for you?

**Comment by omedeiro** [comment]
Yeah that would work!

**Comment by loganbvh** [comment]
I just merged a PR (https://github.com/loganbvh/py-tdgl/pull/24) that adds the two functions listed below. I will upload the changes to pypi soon.

`tdgl.get_current_through_paths()`: https://github.com/loganbvh/py-tdgl/blob/bcea2fff3d0a2823ee02aac4e688a481e48c04e0/tdgl/solution/data.py#L446-L472

and `tdgl.plot_current_through_paths()`:
https://github.com/loganbvh/py-tdgl/blob/bcea2fff3d0a2823ee02aac4e688a481e48c04e0/tdgl/solution/plot_solution.py#L640-L674
