### ISSUE TITLE
CLI Visualization Incorrect Automatic Axis Scales

### ISSUE THREAD

**Issue by Kyroba** [loganbvh/py-tdgl#28]
The XY axis scales are incorrect and do not accurately portray the real size of the geometry. Defining the geometry:
```
# Device geometry
total_width = 100
total_length = 40
ch_width = 5
ch_length = 20

channel1 = (
    tdgl.Polygon(points=box(ch_width, ch_length))
    .translate(dy=-total_length/2-ch_length/2)
    .translate(dx=-total_width/4)
)

channel2 = channel1.scale(xfact=-1)

channel3 = (
    tdgl.Polygon(points=box(ch_width, ch_length))
    .translate(dy=total_length/2 + ch_length/2)
)


film = (
    tdgl.Polygon("film", points=box(total_width, total_length))
    .union(channel1, channel2, channel3)
    .resample(5001)
    .buffer(0)
)
```

The following image is displayed accurately:

![image](https://github.com/loganbvh/py-tdgl/assets/34236089/b639b94e-c1a2-4a11-beac-19e726fff9f7)
![image](https://github.com/loganbvh/py-tdgl/assets/34236089/861cbabd-231d-462e-8c72-6781d669893e)

And this is the output from using CLI (`python -m tdgl.visualize --input "weak-link-zero-current.h5" animate --output "anim.mp4" --quantities ORDER_PARAMETER`):

https://github.com/loganbvh/py-tdgl/assets/34236089/1df78ca3-0e68-4122-bea2-d834aec92861

**Comment by loganbvh** [comment]
In all animations, the axes will be in units of the coherence length. If you would like, I can probably add an option to use real units (e.g. microns) for the axes in animations.

**Comment by Kyroba** [comment]
Ah that makes sense, thanks for the swift response! If you don't mind that would be a nice option to have.

**Comment by Kyroba** [comment]
On the topic of units, the time is dimensionless as stated in the docs. Is there a way to display the real elapsed time in the animation?

**Comment by loganbvh** [comment]
> If you don't mind that would be a nice option to have.

Sure, it will work on this soon.

> the time is dimensionless as stated in the docs. Is there a way to display the real elapsed time in the animation?

The conversion from dimensionless time to seconds depends on the normal state conductivity of the material (\sigma). Because \sigma doesn't affect the dynamics, but only the scaling for the time and voltage units, I made it optional to specify \sigma for a given `tdgl.Layer`. I can probably display the real time in an animation for simulations where \sigma is given by the user.

**Comment by loganbvh** [comment]
Started a PR (https://github.com/loganbvh/py-tdgl/pull/30) for this

**Comment by loganbvh** [comment]
I merged https://github.com/loganbvh/py-tdgl/pull/30, so I am closing this issue
