### ISSUE TITLE
Strange Results with Large Geometry

### ISSUE THREAD

**Issue by Kyroba** [loganbvh/py-tdgl#32]
My understanding of superconducting vortices is that they nucleate from edges and defects in a sample in the presence of a magnetic field. This translates well in py-tdgl when looking at small geometries. However, I was investigating a large shape with dimensions roughly 40x100 um. In the initialization of vortices using high field, it appears that the vortices are generated all over the sample instead of just from the edges. Is this due to imprecision in numerical handling causing 'defects' to appear or something else? Below is the output animation for zero applied current (non-zero vector potential and default epsilon):

### Full Sim
https://github.com/loganbvh/py-tdgl/assets/34236089/87b7fc8b-5e69-41cc-97dd-25883e8b3194

### Sim Start Slowed
https://github.com/loganbvh/py-tdgl/assets/34236089/74d06e74-4585-4531-8c54-650021d8adb5

Could this be the result of a rapid change in applied field?

**Comment by Kyroba** [comment]
Here is the output of APPLIED_VECTOR_POTENTIAL:

https://github.com/loganbvh/py-tdgl/assets/34236089/fbb8ce0f-17cc-407b-92ae-b4d28c099920

**Comment by loganbvh** [comment]
I think this is related to your other question about time-dependent applied vector potential. It is unphysical for the applied field to go from zero to some large value instantaneously, which is effectively what happens in the first time step of the simulation. Above a certain value of the applied field, this results in vortices nucleating in the bulk, which I think is not true to reality as you said. If you were to instead ramp the applied field up from zero over some amount of time, I believe all vortices would come from the edges. I will think about how to add time-dependent applied fields - one subtlety is that there is an additional electric field term proportional to dB/dt that needs to be included. As you pointed out in the other GH issue, you can effectively ramp up the applied field by seeding a simulation with the results of a previous one, but this is cumbersome.

**Comment by loganbvh** [comment]
I am going to close this issue because I have merged https://github.com/loganbvh/py-tdgl/pull/33, which adds support for time-dependent vector potentials
