### ISSUE TITLE
Spatially Varying Thickness and Layers

### ISSUE THREAD

**Issue by Kyroba** [loganbvh/py-tdgl#41]
I was wondering if it is possible to introduce a thickness gradient to the device. For instance, thickness of the thin film is largest at the edges and decreases towards the center, similar to a bowl shape. I understand the thickness value in `tdgl.device` requests a float. Would this kind of change in thickness even be realistic considering how the TDGL is done? 

I was also wondering if it is possible to combine several `tdgl.layer` together to make a Josephson junction for example (in the same plane or even vertically stacked). 

Perhaps I could spatially vary `disorder_epsilon` in `tdgl.solve` to mimic thickness changes but I am not sure how I would go about doing this.

**Comment by Kyroba** [comment]
Also, this could relate to artificial pinning sites that can be introduced into a thin film, like a partially etched geometry. We can do holes which go completely through the thin film but can we do any indents for example?

**Comment by loganbvh** [comment]
Hi @Kyroba,

I can't think of a straightforward way to model thickness gradients given the 2D nature of `tdgl`. `disorder_epsilon` can be used to model spatial inhomogeneity in the zero-field, zero-current superfluid density. A spatial gradient of the critical temperature `T_c(r)` may in some ways mimic a thickness gradient, in the sense that regions with lower T_c will have a lower superfluid density and therefore a smaller magnetic response and thickness-integrated critical current density, just like a region where the film is thinner would. I am not sure what the right mapping from `thickness(r)` to `T_c(r)` would be.

> I was also wondering if it is possible to combine several tdgl.layer together to make a Josephson junction for example (in the same plane or even vertically stacked).

For layers stacked vertically (along the z axis), the answer is definitely no. However it is possible to model planar SNS or SS'S junctions by setting `disorder_epsilon` to a smaller value in the junction region than in the leads. For a more complete way to simulate Josephson junctions, you could take a look at https://github.com/jabirali/geneus

> We can do holes which go completely through the thin film but can we do any indents for example?

Again, I think `disorder_epsilon` is currently the only way to try to model this situation. If you etched, for example, halfway through the film and assume that the material properties of the etched region are the same as the unetched region, then the etched region will have half the thickness-integrated superfluid density of the unetched region (i.e. half the total number of Cooper pairs). It should be possible to find a value for `epsilon(r)` that produces that situation.

**Comment by Kyroba** [comment]
Thank you very much! I had assumed so, but I just wanted to clarify before proceeding. I was hoping to replicate something similar to this paper and compare the solely 2D pyTDGL with their results obtained in COMSOL: 

https://www.researchgate.net/publication/340041249_Time-dependent_Ginzburg-Landau_treatment_of_rf_magnetic_vortices_in_superconductors_Vortex_semiloops_in_a_spatially_nonuniform_magnetic_field?_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6Il9kaXJlY3QiLCJwYWdlIjoiX2RpcmVjdCJ9fQ
