### ISSUE TITLE
Visualization during a simulation

### ISSUE THREAD

**Issue by loganbvh** [loganbvh/py-tdgl#44]
For long-running simulations, it would be nice to have a separate thread/process that plots the current state of the system in real time. I think this can be implemented safely using https://docs.h5py.org/en/stable/swmr.html

**Comment by Kyroba** [comment]
That would definitely be useful. I wonder how fast it updates. Must also keep `options.save_every` a small number to ensure that it can be realtime.

**Comment by loganbvh** [comment]
> I wonder how fast it updates. Must also keep options.save_every a small number to ensure that it can be realtime.

By "real time" I just mean "as fast as data is being saved," so yes it will depend on `options.save_every`

**Comment by loganbvh** [comment]
Implemented in https://github.com/loganbvh/py-tdgl/pull/47
