### ISSUE TITLE
Error: Unable to create group during Solve

### ISSUE THREAD

**Issue by Kyroba** [loganbvh/py-tdgl#48]
I was attempting to make an array of holes in the thin film. I finally managed to do it and here is the output:

![image](https://github.com/loganbvh/py-tdgl/assets/34236089/99d2318a-3e71-4aec-831e-c36f4f15656e)
![image](https://github.com/loganbvh/py-tdgl/assets/34236089/e68a6524-91c8-4c75-ace9-6653ffef7828)

I essentially made an empty list and appended holes to the list using a loop.

The issue arises right at the end of the simulation. Here is the code:
```
from tdgl.sources import ConstantField, LinearRamp

options = tdgl.SolverOptions(
    gpu = True,
    solve_time=400,
    sparse_solver="superlu",
    output_file=os.path.join("Z:/Archive/TDGL Sims/Paper 1", "nobiasTriUP.h5"),
    field_units = "mT",
    current_units="uA",
)

uniform = ConstantField(
    0.6,  
    field_units="mT",
    length_units="um",   # Set your length unit, default is "um"
)

A_applied = (LinearRamp(tmin=0, tmax=200) * uniform)

zero_current_solution = tdgl.solve(
    device,
    options,
    # If applied_vector_potential is given as a single number,
    # it is interpreted to mean the vector potential associated with a
    # uniform out-of-plane magnetic field with the specified strength.
    applied_vector_potential = A_applied,
)

```

and here is the output:
```
Simulating: 100%|█████████████████████████████████████████████████████████████████▉| 400/400 [39:31<00:00,  5.93s/tau ]
Ignoring the following exception in DataHandler.__exit__():
Traceback (most recent call last):
  File "C:\Users\Ca\AppData\Local\Programs\Python\Python310\lib\site-packages\tdgl\solver\solve.py", line 491, in solve
    solution.to_hdf5()
  File "C:\Users\Ca\AppData\Local\Programs\Python\Python310\lib\site-packages\tdgl\solution\solution.py", line 914, in to_hdf5
    self._save_to_hdf5_file(self.path, save_mesh=save_mesh)
  File "C:\Users\Ca\AppData\Local\Programs\Python\Python310\lib\site-packages\tdgl\solution\solution.py", line 901, in _save_to_hdf5_file
    self.device.to_hdf5(group.create_group("device"), save_mesh=save_mesh)
  File "C:\Users\Ca\AppData\Local\Programs\Python\Python310\lib\site-packages\tdgl\device\device.py", line 805, in to_hdf5
    hole.to_hdf5(group.create_group(hole.name))
  File "C:\Users\Ca\AppData\Local\Programs\Python\Python310\lib\site-packages\h5py\_hl\group.py", line 64, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl, gcpl=gcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5g.pyx", line 166, in h5py.h5g.create
ValueError: Unable to create group (name already exists)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[40], line 20
     12 uniform = ConstantField(
     13     0.6,  
     14     field_units="mT",
     15     length_units="um",   # Set your length unit, default is "um"
     16 )
     18 A_applied = (LinearRamp(tmin=0, tmax=200) * uniform)
---> 20 zero_current_solution = tdgl.solve(
     21     device,
     22     options,
     23     # If applied_vector_potential is given as a single number,
     24     # it is interpreted to mean the vector potential associated with a
     25     # uniform out-of-plane magnetic field with the specified strength.
     26     applied_vector_potential = A_applied,
     27 )

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\tdgl\solver\solve.py:491, in solve(device, options, applied_vector_potential, terminal_currents, disorder_epsilon, seed_solution)
    481 if result:
    482     solution = Solution(
    483         device=device,
    484         path=data_handler.output_path,
   (...)
    489         total_seconds=(end_time - start_time).total_seconds(),
    490     )
--> 491     solution.to_hdf5()
    492     return solution
    493 return None

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\tdgl\solution\solution.py:914, in Solution.to_hdf5(self, h5path, save_mesh)
    912 if self.saved_on_disk:
    913     if h5path is None:
--> 914         self._save_to_hdf5_file(self.path, save_mesh=save_mesh)
    915     else:
    916         shutil.copy(self.path, h5path)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\tdgl\solution\solution.py:901, in Solution._save_to_hdf5_file(self, h5file, save_tdgl_data, save_mesh)
    895 serialize_func(
    896     self.disorder_epsilon,
    897     "disorder_epsilon",
    898     group,
    899 )
    900 group.attrs["total_seconds"] = self.total_seconds
--> 901 self.device.to_hdf5(group.create_group("device"), save_mesh=save_mesh)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\tdgl\device\device.py:805, in Device.to_hdf5(self, path_or_group, save_mesh)
    803 for hole in sorted(self.holes, key=attrgetter("name")):
    804     group = f.require_group("holes")
--> 805     hole.to_hdf5(group.create_group(hole.name))
    806 if save_mesh and self.mesh is not None:
    807     self.mesh.to_hdf5(f.create_group("mesh"))

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\h5py\_hl\group.py:64, in Group.create_group(self, name, track_order)
     62 name, lcpl = self._e(name, lcpl=True)
     63 gcpl = Group._gcpl_crt_order if track_order else None
---> 64 gid = h5g.create(self.id, name, lcpl=lcpl, gcpl=gcpl)
     65 return Group(gid)

File h5py\_objects.pyx:54, in h5py._objects.with_phil.wrapper()

File h5py\_objects.pyx:55, in h5py._objects.with_phil.wrapper()

File h5py\h5g.pyx:166, in h5py.h5g.create()

ValueError: Unable to create group (name already exists)
```

![image](https://github.com/loganbvh/py-tdgl/assets/34236089/4bad40ee-7cdd-4f16-9965-1ac460aca731)

**Comment by loganbvh** [comment]
Can you share the code used to create the Device? I think the problem is
that each hole needs a unique name. I thought I had a check for this in the
Device initialization code, but maybe not.

**Comment by loganbvh** [comment]
If you just make the name of each antidot “antidot” + str(i) it should
work. Yeah the simulation runs fine, the error is just happening when
trying to save the Device to the H5 file. Sorry, I thought that I had a
check in Device.__init__ to validate the names of all Polygons, but
apparently not. I will add that soon.

By the way, if you upgrade to the latest version you can plot the results
while the simulation is running by setting tdgl.SolverOptions.monitor =
True. There was also a small bug in v0.6.0 where the dA/dt term was not
being included in the expression for the normal current, so you should
upgrade anyways to get the fix for that bug. You can find more details at
the change log in the online documentation.

**Comment by Kyroba** [comment]
Thank you so much!

**Comment by Kyroba** [comment]
The simultaneous viewing of the simulation is a nice addition, and thanks for the heads up on the bug in 0.6, I have upgraded to the latest version now.

**Comment by Kyroba** [comment]
Is it possible to get an example of how to use `disorder_epsilon`? In the documentation it takes a position from which you can then assign a value between -1 and 1. However, how could you do the same antidot array as above utilizing only the `disorder_epsilon` parameter, this would be useful for cases like blind etching where the hole has not been completely etched through. Can we create polygons and then assign each polygon an epsilon value?

Also, considering YBCO thin films the intrinsic pinning is actually quite high. Can there be an option for random pinning potential (I would assume this is still done through `disorder_epsilon`) across the surface of the simulated film proportional to some scaling factor for both its frequency and amplitude? This would allow for simulations involving the effects of grain sizes etc.

**Comment by loganbvh** [comment]
Hi @Kyroba,

Here is what I would do:

```python
def epsilon(r, *, antidots):
    for antidot in antidots:
        if antidot.contains_points(r)[0]:  # tdgl.Polygon.contains_points() returns an array of length 1 in this case
            return -1
    return 1

device = tdgl.Device(
    "pure_square",
    layer=layer,
    film=film,
    # No holes!
    terminals=[source, drain],
    probe_points=probe_points,
    length_units=length_units,
)

zero_current_solution = tdgl.solve(
    device,
    options,
    # If applied_vector_potential is given as a single number,
    # it is interpreted to mean the vector potential associated with a
    # uniform out-of-plane magnetic field with the specified strength.
    applied_vector_potential = A_applied,
    disorder_epsilon=epsilon,
)
```

I have some more detailed examples of `disorder_epsilon` that I will share soon.

**Comment by loganbvh** [comment]
> Can there be an option for random pinning potential (I would assume this is still done through disorder_epsilon) across the surface of the simulated film proportional to some scaling factor for both its frequency and amplitude? This would allow for simulations involving the effects of grain sizes etc.

Yes, this would be done using `disorder_epsilon` as well. You would just have to define, for example, the spatial distribution of critical temperature or gap value that you want and translate that into a value for \epsilon(\mathbf{r}).

**Comment by loganbvh** [comment]
Two other general comments:

1. There is a limit to the type and strength of pinning that can be described by this so-called "delta-Tc" pinning model. For an overview of other models for pinning, see "Vortices in high-performance high-temperature superconductors" in Rep. Prog. Phys. 79 116501 (2016) (DOI: 10.1088/0034-4885/79/11/116501). I can share a pdf if you don't have access.
2. If regions with \epsilon(r) < 1 are not bigger than ~\xi^2, they will just be proximitized by the surrounding superconductor and the order parameter will not actually be significantly suppressed.

**Comment by Kyroba** [comment]
Thank you! I requested access to the paper but it might be faster to get it from you.

**Comment by loganbvh** [comment]
[Kwok et al. 2016 - Vortices in high-performance high-temperature superconductors.pdf](https://github.com/loganbvh/py-tdgl/files/12842491/Kwok.et.al.2016.-.Vortices.in.high-performance.high-temperature.superconductors.pdf)

**Comment by loganbvh** [comment]
Here's one demonstration of `disorder_epsilon`: [disorder_epsilon.pdf](https://github.com/loganbvh/py-tdgl/files/12842507/disorder_epsilon.pdf)

https://github.com/loganbvh/py-tdgl/assets/20325010/bcdbc902-c9f9-4769-a8bd-ed90c14e37f4

**Comment by Kyroba** [comment]
Thank you for that! I was having trouble understanding how the position r would work after the mesh for the device had already been made, but I guess this isn't even a concern. This is definitely far simpler than I was imagining. Again, thank you for clarifying!

**Comment by loganbvh** [comment]
Added check for unique hole names in https://github.com/loganbvh/py-tdgl/pull/49
