### ISSUE TITLE
ParaView Visualization

### ISSUE THREAD

**Issue by Kyroba** [loganbvh/py-tdgl#50]
I vaguely remember something about loading the hd5 files into ParaView for visualizing in 3D but can't seem to find any mention of it anywhere. I loaded the file into ParaView and of the various readers that were available only 1 seemed to work however it did not seem to import the mesh appropriately. I used this reader:

![image](https://github.com/loganbvh/py-tdgl/assets/34236089/0736f28a-cbc1-4603-8a10-16a87caf0181)

![image](https://github.com/loganbvh/py-tdgl/assets/34236089/93592c1d-ce7b-4e7a-8ab2-53dec9562f4a)

**Comment by loganbvh** [comment]
Hi @Kyroba,

The way I save TDGL data in the HDF5 file is not directly compatible with ParaView. Here is a function you can use to convert a `tdgl` HDF5 file to an XDMF file that can be viewed in ParaView. This requires you to install the [meshio](https://github.com/nschloe/meshio) Python package (`pip install meshio`), then open the XDMF file using the "Xdmf3ReaderS" or "Xdmf3ReaderT" reader in ParaView. Let me know if you have any issues. Eventually I will probably include this functionality in the `tdgl.visualize` CLI tool. 

```python
import os
from typing import Optional

import h5py
import meshio
from tqdm import tqdm

import tdgl
from tdgl.visualization import get_plot_data, Quantity


def convert_to_xdmf(
    path_to_solution: os.PathLike,
    xdmf_path: Optional[os.PathLike] = None,
    dimensionless: bool = False,
) -> None:
    """Convert a tdgl.Solution from HDF5 to XDMF for compatibility with ParaView.
    
    Args:
        path_to_solution: Path to the HDF5 file containing the tdgl.Solution
        xdmf_path: Path to the output XDMF file.
            Defaults to ``path_to_solution.replace('.h5', '-converted.xdmf')``
        dimensionless: Save the mesh in dimensionless units
            (scaled to the coherence length).
    """
    solution = tdgl.Solution.from_hdf5(path_to_solution)
    device = solution.device
    mesh = device.mesh
    points = mesh.sites
    if not dimensionless:
        points = points * device.layer.coherence_length
    cells = [("triangle", mesh.elements)]
        
    if xdmf_path is None:
        xdmf_path = path_to_solution.replace(".h5", "-converted.xdmf")
    
    first, last = solution.data_range

    with h5py.File(path_to_solution, "r") as h5file:
        with meshio.xdmf.TimeSeriesWriter(xdmf_path) as writer:
            writer.write_points_cells(points, cells)
            for step in tqdm(range(first, last + 1), desc="frames"):
                solution.solve_step = step
                t = solution.tdgl_data.state["time"]
                point_data = {}
                for name, quantity in Quantity.__members__.items():
                    data, _, _ = get_plot_data(h5file, mesh, quantity, step)
                    point_data[name.lower()] = data
                writer.write_data(t, point_data=point_data)
```

**Comment by loganbvh** [comment]
Closed by https://github.com/loganbvh/py-tdgl/pull/54
