### ISSUE TITLE
Modify Axis Limits in Visualize

### ISSUE THREAD

**Issue by Kyroba** [loganbvh/py-tdgl#55]
When dealing with large geometries, small holes can sometimes not be visible in the final animation. Zooming in by changing the axis limits would be a nice work around or even a way to highlight holes in the final image?

https://github.com/loganbvh/py-tdgl/assets/34236089/bf32cf1e-0983-4cc6-ae8e-f23924038120

Here you can see it initializes with the effect from the tiny holes, but then quickly becomes invisible.

**Comment by loganbvh** [comment]
This may be due to the type of interpolation used in the animation code. Can you try plotting the solution with `solution.plot_order_parameter(shading="flat")` and `solution.plot_order_parameter(shading="gouraud")` and paste the results below? `tdgl.visualize` uses `"gouraud"`, but I can add an option to specify the shading argument from the command line.

**Comment by Kyroba** [comment]
![image](https://github.com/loganbvh/py-tdgl/assets/34236089/c61b8189-3642-41b2-9ae2-4c5f1c8227e4)
![image](https://github.com/loganbvh/py-tdgl/assets/34236089/e71910fe-056d-46bc-b312-79f3ac3d3d11)
Yes you are right, it looks like it is the interpolation that is removing them. It is hard to tell with these small images, but zooming in definitely shows the holes in the 'flat' shading.

**Comment by Kyroba** [comment]
Also, a CLI for generating an output figure at specific times would be nice instead of just animations if possible.

**Comment by loganbvh** [comment]
Okay, thanks. I will add an option to specify the `shading` in `tdgl.visualize`. I think if you have `shading="flat"` and set a large enough `dpi` and `figsize`, the holes should be visible.

> Also, a CLI for generating an output figure at specific times would be nice instead of just animations if possible.

Yeah, makes sense. Something like `python -m tdgl.visualize --input=<input-path> snapshot --time=100 --quantities order_parameter supercurrent`?

**Comment by Kyroba** [comment]
That's excellent! There is an issue with that command though:
![image](https://github.com/loganbvh/py-tdgl/assets/34236089/87835fd0-faba-43c3-a4b8-c8ee566543da)
![image](https://github.com/loganbvh/py-tdgl/assets/34236089/c2551286-0672-4557-9f8d-a7031ac8fc70)

**Comment by loganbvh** [comment]
Sorry for the confusion - the `snapshot` command doesn't exist yet. I was just clarifying what you were requesting. I will put it on the to-do list

**Comment by Kyroba** [comment]
Perhaps --time can take a list of values so we can generate multiple images in one command? Having the dpi/figsize options would be nice and setting axis limits too. I think it can be beneficial to zoom in from a larger simulated geometry onto a subset of holes to see how the vortices behave near the edges of a hole.

**Comment by loganbvh** [comment]
Closed by https://github.com/loganbvh/py-tdgl/pull/57

**Comment by loganbvh** [comment]
The snapshot command will be added once I merge https://github.com/loganbvh/py-tdgl/pull/60
