### ISSUE TITLE
Post Simulation Probe Points

### ISSUE THREAD

**Issue by Kyroba** [loganbvh/py-tdgl#59]
Is it possible for probe points to be either moved/added after the simulation is done? I would assume this would only require the recalculation of the electric potential over the points at each solve step?

**Comment by loganbvh** [comment]
Closed by https://github.com/loganbvh/py-tdgl/pull/61.

To use this, run

```python
from tdgl.solution.data import DynamicsData
path_to_solution = ...
probe_points = [...]
dynamics = DynamicsData.from_solution(path_to_solution, probe_points=probe_points)
fig, ax = dynamics.plot()
```
