### ISSUE TITLE
Real-time monitor hangs for large geometries

### ISSUE THREAD

**Issue by Kyroba** [loganbvh/py-tdgl#64]
The plotting of data whilst the simulation is running is extremely taxing on my pc. The figures do not even load when simulating geometries 300*xi. This could be due to the density of data and having to output basically 4 different figures, I'm not exactly sure. Perhaps a subsample of the data could be beneficial to improve efficiency? I have not done much testing on this, so it might be working on other machines whilst mine has an error somewhere.

**Comment by loganbvh** [comment]
Can you share an example geometry and simulation parameters?

**Comment by loganbvh** [comment]
And what exactly is the behavior you see? The figure doesn’t show up at all?

**Comment by Kyroba** [comment]
Just a plain 1x1um square film, with xi = 3nm. Mesh is about 1.6 million sites.
```
length_units = "um"
# Material parameters
xi = 0.003
london_lambda = 0.3
d = 0.001
layer = tdgl.Layer(coherence_length=xi, london_lambda=london_lambda, thickness=d, gamma=20)

# Device geometry
total_width = 1
total_length = 1

film = tdgl.Polygon("film", points=box(total_width, total_length))
film = resample_polygon(film, num_points=select_polygon_points(film, xi / 2))

# Current terminals
source = (
    tdgl.Polygon("source", points=box(total_width*0.01, total_length*1.02))
    .translate(dx=-total_length/2)
)
drain = source.scale(xfact=-1).set_name("drain")
#  Voltage measurement points
probe_points = [(-total_length/2 * 0.925, 0), (total_length/2 * 0.925, 0)]
```

```
device = tdgl.Device(
    "pure_square",
    layer=layer,
    film=film,
    holes=antidots,
    terminals=[source, drain],
    probe_points=probe_points,
    length_units=length_units,
)

device.make_mesh(max_edge_length=xi/2)
```
The issue is that the figure window will pop up, but no images are displayed. I left it running for an hour so that enough solve steps were taken for an update of the figure but that did not help. The figure is also extremely laggy. One possibility could be that within the time it is taking to generate 1 figure the amount of solve steps to generate the next figure has already taken place and so it might be cancelling the previous one and running again (I highly doubt this- just a possibility). I would imagine it shouldn't take too long to actually generate the figure.

**Comment by Kyroba** [comment]
A simple workaround is to just not worry about monitoring for larger sizes, as the simulation time taken to see any changes would make it less impactful. I am just curious to see if it is something only I am experiencing.

**Comment by loganbvh** [comment]
The reason that figure is laggy is that the monitor subprocess just sits in a loop checking if any new data is present. I have opened a pull request (https://github.com/loganbvh/py-tdgl/pull/65) adding an `options.monitor_update_interval` parameter to set how often this loop tries to update the figure. In between updates, you should be able to interact with the figure without lag. For example, if you have a big simulation where the time between save intervals is a minute, you could set `options.monitor_update_inverval = 60` seconds.

Want to give that a try? In a new conda env for testing, 

```
pip install git+https://github.com/loganbvh/py-tdgl.git@monitor
```

**Comment by Kyroba** [comment]
That is much, much better. The figure window is easily movable now, no lag. However, my pc still has problems generating the images so I tested it on another computer with a comparable CPU but it has no graphics card - the figure works as intended on that. So there must be something else wrong specific to my pc that I need to figure out. Thanks for that option!

**Comment by loganbvh** [comment]
If possible, it might be worth checking which matplotlib backend is running on the two computers you tried. You can check by running the following from the command line (not in a Jupyter notebook).

```python
import matplotlib

matplotlib.get_backend()
```

**Comment by loganbvh** [comment]
I will merge this change and make a new release in the next day or two.

**Comment by loganbvh** [comment]
Closing: https://github.com/loganbvh/py-tdgl/releases/tag/v0.8.0
