### ISSUE TITLE
High Fluxoid Error with No Screening 

### ISSUE THREAD

**Issue by Kyroba** [loganbvh/py-tdgl#66]
For a large geometry (1um square with 3nm coherence length, 6nm hole pattern), the hole fluxoid error is high - suggesting that screening is necessary. I chose parameters such that effective magnetic screening length = 90 microns.
![image](https://github.com/loganbvh/py-tdgl/assets/34236089/76249804-b587-4d85-9630-ce5cbd47ca80)

Is this an issue with how I am calculating the fluxoid or do I really need screening for these simulations. Below are images of the device and order parameter at a specific time (with bias).
![device3](https://github.com/loganbvh/py-tdgl/assets/34236089/de347b67-cadd-484a-9d79-4972bf05d57c) 
![100uAbiaspsi3_25](https://github.com/loganbvh/py-tdgl/assets/34236089/2ac8066f-d5a9-43a0-9cc7-bd03d20b63cc)

**Comment by loganbvh** [comment]
Given the long magnetic screening length, I don't think this is due to neglecting screening. I'm pretty sure this is just discretization/interpolation error. When vortices are so densely packed, the interpolation required for the fluxoid calculation may introduce large errors. 

If you just want to figure out how many flux quanta are in each hole, you can use solution.boundary_phases() to evaluate the phase of the order parameter along the film and hole boundaries.

**Comment by loganbvh** [comment]
e.g.

```python
boundary_phases = solution.boundary_phases(delta=True)
hole_phase_difference = boundary_phases["antidot12"].phases[-1]
fluxoid = hole_phase_difference / (2 * np.pi)
```

From the quickstart notebook:

<img width="720" alt="image" src="https://github.com/loganbvh/py-tdgl/assets/20325010/93ded342-f60d-419d-a71c-8d6963151ceb">

**Comment by Kyroba** [comment]
Thanks Logan, it is taking a long time just to calculate the fluxoid for 1 antidot but I will post the result here when it is done.

**Comment by loganbvh** [comment]
That function calculates the boundary phases for all holes, so it will take a long time if there are many holes in a big mesh. You can just copy the code in the function to apply it to one hole at a time if you'd like.

**Comment by loganbvh** [comment]
```python
def get_polygon_boundary_phase(solution: tdgl.Solution, polygon_name: str, delta: bool = False) -> np.ndarray:
    device = solution.device
    boundary_indices = device.boundary_sites()
    psi = solution.tdgl_data.psi
    theta = np.angle(psi)
    indices = boundary_indices[polygon_name]
    phases = np.unwrap(theta[indices])
    if delta:
        phases -= phases[0]
    return phases
```

**Comment by Kyroba** [comment]
![image](https://github.com/loganbvh/py-tdgl/assets/34236089/4ce732bd-253d-4de4-83ca-2b4017f0a544)
Seems like it worked (took 10min), and using the function you provided:
![image](https://github.com/loganbvh/py-tdgl/assets/34236089/04cfeae9-8070-4612-8db2-6d0a14982095)
