### ISSUE TITLE
tdgl.visualize --output not recognized

### ISSUE THREAD

**Issue by Kyroba** [loganbvh/py-tdgl#67]
I think this issue may have risen after the `snapshot` feature was implemented. The command I use to produce animations no longer works as the --output argument is not recognized. Removing the output argument does not work either as it does for `snapshot` since it fails to produce an animation without a file to dump to.

`python -m tdgl.visualize --input "nobiasExp3.h5" animate --output "anim.mp4" --quantities ORDER_PARAMETER`

![image](https://github.com/loganbvh/py-tdgl/assets/34236089/82e06c82-a105-4c44-9e3d-e24f6d389a36)
![image](https://github.com/loganbvh/py-tdgl/assets/34236089/4d84ae13-6a52-47f2-a2e5-48fdc92093aa)

**Comment by loganbvh** [comment]
It should work if you move the output argument before the animate command.
I changed the order of the arguments. Sorry for any confusion

**Comment by Kyroba** [comment]
Thanks, I just realised the change in the warning; didn't see it.
