### ISSUE TITLE
Pixel Current Artefact

### ISSUE THREAD

**Issue by Kyroba** [loganbvh/py-tdgl#68]
When attempting a nanoSQUID simulation, I noticed a strange current spike stuck in a specific location of the loop. This current spike does not move or react to applied fields. You can see it just below the left weak-link (25mT applied field no bias):

![image](https://github.com/loganbvh/py-tdgl/assets/34236089/59eb0984-1b25-49c4-a1c1-9854874a8fb6)

The first thing I went to check was the mesh to see if there is some kind of dislocation:

![image](https://github.com/loganbvh/py-tdgl/assets/34236089/0c27204d-9346-45f7-9beb-057643b68c8b)

But it doesn't seem like anything is wrong. Changing mesh parameters moves the artefact around, but I can never get rid of it. I have also iteratively removed each polygon to see if something was causing the issue, and to my surprise, I saw this artefact in a plain square film with no holes. The only way I was able to get rid of it was to use entirely different xi and lambda values. 

```
length_units = "nm"
# Material parameters
xi = 25
london_lambda = 100
d = 5
layer = tdgl.Layer(coherence_length=xi, london_lambda=london_lambda, thickness=d, gamma=10)
```

**Comment by loganbvh** [comment]
Hi @Kyroba,

I think this type of artifact happens when the time step is slightly too big, making the numerics slightly unstable. I would try re-running the simulation with `options.dt_max` set to, for example, 80% of the value used for the simulation shown above.

**Comment by Kyroba** [comment]
I varied dt_max from default 0.1 to 0.05, 0.01, 0.001 yet the artefact was still there. Didn't seem to change in size or position at all either.

**Comment by loganbvh** [comment]
Can you try increasing the `smooth` parameter in `device.make_mesh()`?

**Comment by loganbvh** [comment]
Also, can you paste the results of `solution.dynamics.plot_dt()`? Thanks

**Comment by Kyroba** [comment]
I changed the `smooth` parameter from 100 to 1000 but still the same result:
![image](https://github.com/loganbvh/py-tdgl/assets/34236089/1fba40bf-0561-4a5a-987d-418704095541)

Here is the output from `solution.dynamics.plot_dt()`. I didn't run the simulation to completion, only 10%, but I think it is enough to show the problem:
![image](https://github.com/loganbvh/py-tdgl/assets/34236089/9afbc725-5bc3-4e1a-8ac1-d4e442758a3d)

**Comment by loganbvh** [comment]
Can you try either `options.dt_max = 5e-4` or resampling the film and hole boundary to have ~30% more points?

The basic problem is that the current density is defined on the edges of the mesh. For plotting, I need to sort of interpolate the current density to evaluate it at the mesh sites rather than edges. This is done by averaging the current density over each edge that's connected to a given mesh site, see below. In certain cases (I think when one or more of the triangles incident to a site is very long/narrow), this average produces artifacts.

https://github.com/loganbvh/py-tdgl/blob/b7792610621d7649661ee276fd72a886a975cb46/tdgl/finite_volume/mesh.py#L203-L243

**Comment by Kyroba** [comment]
That dt_max value did the trick! Your explanation also makes a lot of sense. Thank you!

**Comment by loganbvh** [comment]
So for a rule of thumb, I would say that if you see this type of artifact, look at `solution.dynamics.plot_dt()` and try setting `options.dt_max` somewhere near the median of the distribution of `dt` values.
