### ISSUE TITLE
Does not work with pint version 0.24

### ISSUE THREAD

**Issue by omansikk** [loganbvh/py-tdgl#78]
Running quickstart.ipynb on Colab results in the error:

```
AssertionError                            Traceback (most recent call last)

[<ipython-input-24-3e6395c7c2a1>](https://localhost:8080/#) in <cell line: 11>()
      9 )
     10 # If you do not provide an applied_vector_potential, tdgl defaults to zero applied field.
---> 11 zero_field_solution = tdgl.solve(
     12     device,
     13     options,

1 frames

[/usr/local/lib/python3.10/dist-packages/tdgl/solver/solver.py](https://localhost:8080/#) in __init__(self, device, options, applied_vector_potential, terminal_currents, disorder_epsilon, seed_solution)
    250 
    251         J_scale = 4 * ((ureg(current_units) / length_units) / K0).to_base_units()
--> 252         assert "dimensionless" in str(J_scale.units), str(J_scale.units)
    253         J_scale = J_scale.magnitude
    254         self.current_func = lambda t: {

AssertionError:
```
The error also occurred on two separate devices with pint freshly installed. Clearly the error has something to do with units, so I tried installing the previous version (0.23), which seemed to fix the problem.

**Comment by rsathyan121** [comment]
Confirming the same error, which occurs in the tutorial file, but is fixed by using Pint 0.23.

**Comment by loganbvh** [comment]
Thanks for reporting this. I've opened a Pull Request that will fix the issue: https://github.com/loganbvh/py-tdgl/pull/79. I will merge it and push the new version to PyPI in about an hour. In the meantime, `pip install pint==0.23` is a good workaround.

**Comment by loganbvh** [comment]
Closing via https://github.com/loganbvh/py-tdgl/pull/79
