### ISSUE TITLE
Replicating SQUID loop result in paper

### ISSUE THREAD

**Issue by Rende410** [loganbvh/py-tdgl#84]
Hello, I am still getting to familiarise with pyTDGL, and one of the things i tried to do in the process was to try and replicate the results of the SQUID loop in the paper (https://doi.org/10.1016/j.cpc.2023.108799).

I tried to create a similar structure from scratch with notches at the two sides of the loop as below:
![image](https://github.com/loganbvh/py-tdgl/assets/170619382/45ffd923-609d-4fe6-a8af-23a81c5e5d08)

However I cannot get a similar results as in  Figure 5 of the paper. I have used largely the same parameters as in the paper for coherence length, penetration depth and thickness etc. While I can observe a localisation of the currents on one side of the loop, I cannot observe the periodic switching of the currents between the two sides, as shown in Figure 5 of the paper. What I can only observe is a single voltage spike with no periodic switching as below.

![image](https://github.com/loganbvh/py-tdgl/assets/170619382/bb75d5b9-5c49-4459-9452-9400456a1d96)
![image](https://github.com/loganbvh/py-tdgl/assets/170619382/a466758a-8ef9-48f7-ad74-cb79ac33eb09)

I have tried playing around with the bias current and/or applied field with not much effect. Is there something I am missing out? 

Another thing I would like to ask is how was panel 5i generated? I suppose it was achieved by running the simulation for several tries while changing the field and bias current and recording the average generated voltage?

Thanks in advance!

**Comment by loganbvh** [comment]
Hi @Rende410,

Here is the actual Jupyter notebook I used to make the figure: https://gist.github.com/loganbvh/a91a8f79d851e8f38359cfc18fab575f. I hope that you can use this as a starting point.

Each pixel in Figure 5(i) is the average voltage for single TDGL simulation at a given value of B_z and I_bias. This type of 2D sweep takes a long time of course. I included it in the paper as a proof of principle. I ran the simulations for that figure on a compute cluster, where each column in the image was run on a different CPU in the cluster.

**Comment by Rende410** [comment]
Hi @loganbvh ,

Thanks for the notebook, I was able to figure out what went wrong with my own version and could replicate the periodic fluctuations now. While looking through yours, I noticed that you defined the B field as a function where it is constant within the loop and scales as cos(lead_angle) outside of it. How would this differ from say, just having a constant uniform B-field all around, even outside the loop? Is this definition of decaying B-field outside the loop essential to produce the V-B curve?

Thanks!

**Comment by loganbvh** [comment]
I don't remember how big of an effect the angle of the leads makes - you can try it yourself. For some combination of parameters, you will end up getting a bunch of vortices in the leads, which will ultimately change the IV curve.

**Comment by loganbvh** [comment]
Closing this issue. Feel free to re-open if needed

**Comment by ce-forge** [comment]
I've noticed that there has been a change in the shapely package when installing python 3.12;
You're nanoSQUID has rounded weak-links whereas with the new version of shapely it results in a sharp edge.
